### ISSUE TITLE
Using single quotes in a label causes a parsing error

### ISSUE THREAD

**Issue by Fermain** [davidenke/astro-decap-collection#4]
In situations where a `'` single quote char is used within a field label, the parser fails. 

I noticed this during testing as many of my test project labels are formed like "Author's Name".

Reproduction:

```yaml
collections:
  - name: "example"
    label: "Example Case"
    folder: "src/content/examples"
    fields:
      - name: "valid_field"
        label: "plain string"
        widget: "hidden"
      - name: "invalid_field"
        label: "string containing ' quote"
        widget: "hidden"
```
